name: Pipeline
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      Deploy:
        type: boolean
        description: "Deseja que faça deploy?"
        required: true
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:      
    - name: Checkout do codigo
      uses: actions/checkout@v5.0.0
    - name: Login Docker
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: builda da imagem
      uses: docker/build-push-action@v5.3.0
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: | 
                vinidows/pipeline041:v${{ github.run_number }}
                vinidows/pipeline041:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Checkout do codigo
      uses: actions/checkout@v5.0.0      
    - name: Configuração do Kubernetes
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.K8S_CONFIG }}
    - name: Execução do manifesto
      uses: Azure/k8s-deploy@v5
      with:
        manifests: |
            ./k8s/deployment.yaml
        images: |
          vinidows/pipeline041:v${{ github.run_number }}


        

      
  
